const RESTAURANT_ACTION_TYPES = {
    FETCH_RESTAURANTS_START: 'FETCH_RESTAURANTS_START',
    FETCH_RESTAURANTS_SUCCESS: 'FETCH_RESTAURANTS_SUCCESS',
    FETCH_RESTAURANTS_FAILURE: 'FETCH_RESTAURANTS_FAILURE',
    SET_CURRENT_RESTAURANTS: 'SET_CURRENT_RESTAURANTS'
};

export default RESTAURANT_ACTION_TYPES
